from typing import List, Optional

class Schedule:
    base_url: str = ...
    def create(self, params: dict) -> Optional[dict]: ...
    def delete(self, task_id: int) -> None: ...
    def get_specs(self, task_id: int) -> dict: ...
    def get_list(self) -> List[dict]: ...
    def update(self, task_id: int, params: dict) -> dict: ...
