import logging
from typing import List

import schema

from pythonanywhere.task import Task

logger: logging.Logger = ...
tabulate_formats: List[str] = ...

class ScriptSchema(schema.Schema):
    boolean: schema.Or = ...
    hour: schema.Or = ...
    minute_required: schema.And = ...
    minute: schema.Or = ...
    id_required: schema.And = ...
    interval: schema.Or = ...
    string: schema.Or = ...
    tabulate_format: schema.Or = ...
    def convert(string: str) -> str: ...
    def validate_user_input(self, arguments: dict) -> dict: ...

def get_logger(set_info: bool) -> logging.Logger: ...
def get_task_from_id(task_id: int) -> Task: ...
