from typing import List, Optional

from typing_extensions import Literal

from pythonanywhere.schedule_api import Schedule

class Task:
    command: Optional[str] = ...
    hour: Optional[int] = ...
    minute: Optional[int] = ...
    interval: Optional[Literal["daily", "hourly"]] = ...
    enabled: Optional[bool] = ...
    task_id: Optional[int] = ...
    can_enable: Optional[bool] = ...
    expiry: Optional[str] = ...
    extend_url: Optional[str] = ...
    logfile: Optional[str] = ...
    printable_time: Optional[str] = ...
    url: Optional[str] = ...
    user: Optional[str] = ...
    schedule: Schedule = ...
    def __init__(
        self, *, command=None, hour=None, minute=None, disabled=None, task_id=None
    ) -> None: ...
    def create_schedule(self) -> None: ...
    def delete_schedule(self) -> None: ...

class TaskList:
    tasks = List[Task]
    def __init__(self) -> None: ...
